dist: bionic
language: node_js
node_js:
  - 12
branches:
  only:
  - master
  - claiming-process
cache:
  yarn: true
  directories:
  - "$HOME/.electron"
  - "$HOME/.cache"
env:
  - ELECTRON_ENABLE_LOGGING=true TRAVIS=true
services:
  - xvfb
addons:
  apt:
    packages:
    # - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn ci