dist: bionic
language: node_js
node_js:
  - 12
branches:
  only:
  - master
  - claiming-process
cache:
  yarn: true
  directories:
  - "$HOME/.electron"
  - "$HOME/.cache"
env:
  - RUST_LOG=error ELECTRON_ENABLE_LOGGING=true TRAVIS=true
services:
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
    # - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
before_script:
- bash ci/initializeWitnet.sh https://github.com/witnet/witnet-rust/releases/download/0.9.0-b/witnet-0.9.0-b-x86_64-unknown-linux-gnu.tar.gz
script:
- yarn ci